services:
  - type: web
    name: restaurant-orders
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ANTISPAM_LIMIT
        value: "2"
      - key: ANTISPAM_WINDOW_MINUTES
        value: "5"
