# render.yaml
services:
  - type: web
    name: coworking-orders
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: FLASK_ENV
        value: production
